List<String> quotes = [
  "The only way to do great work is to love what you do. – Steve Jobs",
  "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
  "Your limitation—it’s only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "It does not matter how slowly you go, as long as you do not stop. – Confucius",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The only impossible journey is the one you never begin. – Tony Robbins",
  "In the middle of difficulty lies opportunity. – Albert Einstein",
  "The journey of a thousand miles begins with one step. – Lao Tzu",
  "Everything has beauty, but not everyone can see. – Confucius",
  "Life is not about finding yourself. Life is about creating yourself. – George Bernard Shaw",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Opportunities don't happen, you create them. – Chris Grosser",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The best revenge is massive success. – Frank Sinatra",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh",
  "It always seems impossible until it is done. – Nelson Mandela",
];
